site_name: recipeai
site_description: CRUD
repo_url: https://github.com/rankam/recipe-ai
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/rankam">rankam</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
