# Generated by Django 2.1.11 on 2019-11-19 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonIngredientNutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('common_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.CommonIngredient')),
            ],
            options={
                'db_table': 'common_ingredient_nutrient',
            },
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('unit_type', models.CharField(max_length=160)),
            ],
        ),
        migrations.AddField(
            model_name='commoningredientnutrient',
            name='nutrient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Nutrient'),
        ),
    ]
