# Generated by Django 2.1.11 on 2019-11-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20191119_1054'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commoningredientnutrient',
            table='recipes_common_ingredient_nutrient',
        ),
    ]
