# Generated by Django 2.1.11 on 2020-05-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20191119_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercommoningredient',
            name='is_available',
        ),
    ]
