# Generated by Django 2.1.11 on 2020-05-16 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_remove_usercommoningredient_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIngredientCommonIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.CommonIngredient')),
                ('recipe_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='user_ingredient_common_ingredient',
            field=models.ManyToManyField(to='recipes.UserIngredientCommonIngredient'),
        ),
    ]
