# Generated by Django 3.0.6 on 2020-05-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20200516_1923'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usercommoningredient',
            constraint=models.UniqueConstraint(fields=('user', 'common_ingredient'), name='user_common_ingredient'),
        ),
    ]
