# Generated by Django 3.0.6 on 2020-05-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20200518_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='name',
            field=models.CharField(max_length=160, primary_key=True, serialize=False),
        ),
    ]
