# Generated by Django 3.0.6 on 2020-05-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20200519_2215'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='nutrient',
        #     name='id',
        #     field=models.AutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID'),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='nutrient',
        #     name='name',
        #     field=models.CharField(max_length=160, unique=True),
        # ),
    ]
