# Generated by Django 3.0.6 on 2020-05-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20200519_2220'),
    ]

    operations = [
        # migrations.AddConstraint(
        #     model_name='nutrient',
        #     constraint=models.UniqueConstraint(fields=('name',), name='name'),
        # ),
    ]
