# Generated by Django 3.0.6 on 2020-05-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20200519_2221'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='nutrient',
        #     name='name',
        # ),
        # migrations.RemoveConstraint(
        #     model_name='nutrient',
        #     name='name',
        # ),        
        # migrations.AddField(
        #     model_name='nutrient',
        #     name='id',
        #     field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),        

    ]
