# Generated by Django 3.0.6 on 2020-05-19 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20200519_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoningredientnutrient',
            name='common_ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.CommonIngredient'),
        ),
        migrations.AddConstraint(
            model_name='commoningredientnutrient',
            constraint=models.UniqueConstraint(fields=('nutrient', 'common_ingredient'), name='nutrient_common_ingredient'),
        ),
    ]
