# Generated by Django 3.0.6 on 2020-05-22 14:52

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_commoningredient_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='common_ingredients',
            field=models.ManyToManyField(null=True, to='recipes.CommonIngredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(null=True, to='recipes.Ingredient'),
        ),
    ]
